### ISSUE TITLE
Bitwarden does not show entries, freeze while searching directly after logging in, Linux Ubuntu

### ISSUE THREAD

**Issue by 123pati** [ErnWong/dotfiles#15]
Hi,
directly after logging in in Bitwarden in Linux(Ubuntu) the program starts searching for entries.
But it doesn´t show any entries. I can´t use Bitwarden. It continues on to search for entries...

I installed Bitwarden a few times at snap store. Now I downloaded the program and installed it through the terminal. Same problem.

I am an absolute beginner and no IT Pro, so if there are some easy/simple hints to fix the problem I would be glad about the help but please write in simple words an no IT acronyms or too complicated technical terminology.

Thank you a lot! : )

Patrizia

**Comment by ErnWong** [comment]
Hi Patrizia,

Although I'm not a Bitwarden expert and this page might not be the most appropriate place to ask for help about Bitwarden, I'm happy to suggest some ideas that might help lead you to a better direction:

## Bitwarden's web version

Have you tried using Bitwarden from the website? https://vault.bitwarden.com/#/login While this might not be what you're looking for, if the web version works, then at least you've got something you can use in the meantime until the problem is resolved. It will also help you figure out whether it is a problem with the Bitwarden desktop app, or whether it's the Bitwarden system in general.

## Bitwarden's community forums

There seems to be a bunch of other Bitwarden users that are helping each other with various issues:

https://community.bitwarden.com/c/support/pm-ask-the-community/62

I noticed in particular that there was someone posting a similar problem as you on that forum: https://community.bitwarden.com/t/desktop-app-on-linux-not-working/65491/6 . Have you tried running their solution?

> 1. Ubuntu Software > Installed > Bitwarden > Permissions - turn on "Read, add, change or remove saved passwords"
> 2. Run the following: `sudo snap connect bitwarden:password-manager-service`

Apparently that fixed the problem for some people, but not for everyone. It looks like they're [working on a better fix](https://github.com/bitwarden/clients/issues/8651) for that problem at the moment but the fix isn't ready yet, so if this turns out to be the same problem as what you're facing, then you might have to wait a bit, and try reinstalling Bitwarden after a day or two.

## Bitwarden's support

If you don't think the above is the same problem as described in the forums, and you tried posting on the forum but didn't get any reply, or if you'd rather not post on the public forum, then another option might be worth reaching out to Bitwarden's support by clicking "Contact support" on the right side of the following page: https://bitwarden.com/help/
![image](https://github.com/ErnWong/dotfiles/assets/2609018/8aac4372-839f-4a7a-9343-f25de41c7310)

## Bitwarden's bug reporting system

If the above methods didn't get you much luck, I'd say the last resort is to file a bug report to https://github.com/bitwarden/clients/issues

I'd keep that as a last resort because we don't want to give the programmers extra work looking at new bug reports if it's something that the support team or the community can respond better to.

----

I think that's all the help I can give you at the moment and with the time I have... I wish you good luck!

**Comment by ErnWong** [comment]
By the way, if you don't mind me asking, I'm now very curious: How did you manage to find my page? Not criticizing or anything :) I'm just very curious, as I wouldn't have thought that this page would come up in search engines.

**Comment by 123pati** [comment]
Oh thanks, changing the permission fixed the problem : )) Thank you!
How I found your page...? I thought this is a generell page where problems concerning Bitwarden can be diskussed...
But as I am not in to IT, maybe I took a wrong link etc.
Actually I clicked at the Bitwarden App the Button "held" than the button "report error" afterwords I was forwarded to this page "https://github.com/bitwarden/clients/issues". Somehow after registration I landed here... :D

Thanks again! Despite this is not the correct page... : )
Patrizia

**Comment by ErnWong** [comment]
Sweet, glad that it fixed the problem for you!

Ah I see. Yeah, I think you did the right thing and clicked the correct button to go to the page https://github.com/bitwarden/clients/issues. I imagine there must've been some weird glitch on GitHub where after registration, it redirected you to a completely different page for some reason. But that's algoods, software can be weird at times.

Wish you all the best
